### ISSUE TITLE
Handle loss of access to the camera.

### ISSUE THREAD

**Issue by jack-oquin** [ros-drivers/axis_camera#1]
If the camera is unavailable on the network when the driver starts, it should initiate a slow poll waiting for it to respond.

Similarly, if the device stops sending images, the driver should wait in a slow poll loop until access is recovered and the camera reconnected.

**Comment by awesomebytes** [comment]
This was implemented and merged already :)

I even tried:

    [WARN] [WallTime: 1430926296.123376] Error opening URL http://10.68.0.6/mjpg/video.mjpg?fps=0&resolution=640x480Possible timeout.  Looping until camera appears

And it loops waiting.
