### ISSUE TITLE
atkin _make fails with following message in hydro - ubuntu

### ISSUE THREAD

**Issue by anfederman** [ros-drivers/axis_camera#27]
CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a package configuration file provided by
  "camera_info_manager_py" with any of the following names:

```
camera_info_manager_pyConfig.cmake
camera_info_manager_py-config.cmake
```

  Add the installation prefix of "camera_info_manager_py" to
  CMAKE_PREFIX_PATH or set "camera_info_manager_py_DIR" to a directory
  containing one of the above files.  If "camera_info_manager_py" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  axis_camera/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
Invoking "cmake" failed

**Comment by mohammad-h-b** [comment]
> You need to install the camera_info_manager_py package. On Ubuntu, do it this way:
> 
> ```
> $ sudo apt-get install ros-hydro-camera-info-manager-py
> ```
> 
> If you want to build it from source, add this github repository to your catkin workspace:
> 
> * https://github.com/ros-perception/camera_info_manager_py.git

I have the same problem [here](https://github.com/NVlabs/Deep_Object_Pose/issues/161).

**Comment by habibmuhammadthariq** [comment]
> You need to install the camera_info_manager_py package. On Ubuntu, do it this way:
> 
> ```
> $ sudo apt-get install ros-hydro-camera-info-manager-py
> ```
> 
> If you want to build it from source, add this github repository to your catkin workspace:
> 
>     * https://github.com/ros-perception/camera_info_manager_py.git

I got this issue in ros noetic and build the camera-info-manager-py from github worked for me
