### ISSUE TITLE
PTZ Processing Speed

### ISSUE THREAD

**Issue by skelly32** [ros-drivers/axis_camera#36]
Is there a way to force the PTZ operation to happen more smoothly? I wrote my own teleop procedure for the camera, and currently it seems to execute a pan or tilt operation once every second to a few seconds. It also is buffering commands a bit even though the subscribed queue size is 1 (from axis_ptz.py), so I'm guessing the camera is imposing some buffer. Is this slow delay a function of the camera hardware or the web interface used to send commands? 

Thanks!

**Comment by awesomebytes** [comment]
I believe the web interface makes it a bit slow, "many" steps are involved from sending a command until it gets executed in the camera PTZ. If you find any way on making this faster I'll be glad of merging a pull request or even taking a look at it myself.
