### ISSUE TITLE
publisher should be created with an explicity keyword argument 'queue_size'

### ISSUE THREAD

**Issue by CatherineH** [ros-drivers/axis_camera#41]
I'm having trouble viewing images from the axis driver, and I'm just trying to cover all issues.

When I launch:

```
roslaunch axis_camera axis.launch hostname:=axis_camera_hostname
```

I get the error:

```
/home/cholloway/workspace/axis_camera/src/axis_camera/nodes/axis.py:156: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.pub = rospy.Publisher("image_raw/compressed", CompressedImage, self)
```

**Comment by awesomebytes** [comment]
Hello, that warning should be fine, should not be giving you any issue, you could fork the project and put a queue_size=5 for example, just to get rid of the warning.

I would suggest you to first try to view the image of the camera in the web browser, if that works, get the url of that image stream (I googled for my model of camera and _camera stream url_) and try to open the stream with something else, e.g.: vlc

I also created this package:
http://wiki.ros.org/video_stream_opencv

Which just opens video streams of different types with opencv, you can even use the python test file (no ROS needed) just to try if that stream actually can be read. I need to work on adding in this package a launch file for that and some docs, as it actually performs better than this package.

This package tries to open the url:
https://github.com/ros-drivers/axis_camera/blob/master/nodes/axis.py#L34-L38
```
        self.url = 'http://%s/mjpg/video.mjpg' % self.axis.hostname
        self.url += "?fps=0&resolution=%dx%d" % (self.axis.width, 
                                                            self.axis.height)
```
Which may be incorrect in some camera/camera configuration. I think that's the main possibility for your node to not be working

**Comment by awesomebytes** [comment]
Closing this issue, the queue_size error should be gone in the next release too.
