### ISSUE TITLE
Request of next release to indigo

### ISSUE THREAD

**Issue by wkentaro** [ros-drivers/axis_camera#46]
Could you please work for this?
I need this change. https://github.com/ros-drivers/axis_camera/pull/38

**Comment by bcfjohns** [comment]
I could also use this fix. Thanks.

**Comment by awesomebytes** [comment]
I'll try to look into it during the next days, probably from Monday

**Comment by tonybaltovski** [comment]
@k-okada could you bloom a 0.2.1 release for Indigo?

**Comment by k-okada** [comment]
@tonybaltovski I asked a release repository owner to give you a write permission https://github.com/ros-drivers-gbp/axis_camera-release/issues/1
Once you get a permission, would you run bloom-release for indigo?
Thank in advance

**Comment by tonybaltovski** [comment]
@k-okada, I will, thank you!
