### ISSUE TITLE
ImportError: No module named camera_info_manager

### ISSUE THREAD

**Issue by hoppss** [ros-drivers/axis_camera#53]
My camera is camera Axis M10XX, not a ptz type .
I meet a error like follwing. 
File "/home/robot/axisM10/src/axis_camera/nodes/axis.py", line 13, in <module>
    import camera_info_manager
ImportError: No module named camera_info_manager

my ros version is indigo, I have installed  camera-info-manager pkg use apt tool,
but this error still exist.

can you tell me how to solve this problem?
Thank you sincerely

**Comment by hoppss** [comment]
I solved.

I need to install pkg "camera_info_manager_py"

**Comment by Hiroaki-K4** [comment]
@hoppss 
Hi.
How to install pkg "camera_info_manager_py"?
Using 'apt install'?

**Comment by Hiroaki-K4** [comment]
I solved.
`git clone https://github.com/ros-perception/camera_info_manager_py`
and locate under src folder.
