### ISSUE TITLE
Axis Camera for Ros Melodic

### ISSUE THREAD

**Issue by perfalle** [ros-drivers/axis_camera#59]
Hi,
Apparently there is no package "ros-melodic-axis-camera" for Ubuntu (18.04.03 LTS).
Also it is not listed at http://wiki.ros.org/axis_camera

Is it planned to bring axis camera to Melodic?

Thanks!

**Comment by k-okada** [comment]
released on melodic  https://github.com/ros/rosdistro/pull/23552
