### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by tonybaltovski** [ros-drivers/axis_camera#60]
@k-okada, I noticed this was marked as orphaned, @civerachb-cpr and/or myself would be interesting in helping out as we deal with these cameras often.

**Comment by k-okada** [comment]
@tonybaltovski thaks for offer! I have added you and @civerachb-cpr. Please add your name (and may be remove orphaed team?) and keep maintain this package.

**Comment by tonybaltovski** [comment]
Thanks @k-okada !!!
