### ISSUE TITLE
support for python3?

### ISSUE THREAD

**Issue by zoombinis** [ros-drivers/axis_camera#63]
axis.py tries to import: `import urllib2`

but since python 3 that library is broken into parts and cannot be imported that way:

https://stackoverflow.com/a/2792652

Python 2 is no longer supported as of January 2020

**Comment by Hiroaki-K4** [comment]
@zoombinis
Hi.
Did you remake axis_camera by using python3?

**Comment by civerachb-cpr** [comment]
When we update for Noetic we'll be fixing these issues and moving to Python3.  Python2 is still usable by necessity in Melodic (python2 being used throughout Ubuntu 18.04), so I don't think we'll be backporting those changes unless absolutely necessary.

**Comment by Hiroaki-K4** [comment]
Hi @civerachb-cpr 
I'm trying to make axis_camera for melodic compatible with python3, but is there any obstacle? For example, package dependencies.

**Comment by Hiroaki-K4** [comment]
ok, I understood.
