### ISSUE TITLE
ros-melodic-axis-camera not current with teleop.py commit  ee524a7fce690b2fab5eb20f7b8ea18b3837fe71

### ISSUE THREAD

**Issue by gmetts** [ros-drivers/axis_camera#65]
Hello, 

Currently the change 3 months ago to fix the [error in teleop.py](https://github.com/ros-drivers/axis_camera/commit/ee524a7fce690b2fab5eb20f7b8ea18b3837fe71) is not being tracked on ros-melodic-axis-camera. Would it be possible to fix this? I have an implementation that I would like to be fully supported by the axis_camera package without needing replacement of the teleop.py node. 

Thanks,

Grant

**Comment by civerachb-cpr** [comment]
We're working on releasing it now. Sorry about the delay!

**Comment by gmetts** [comment]
No worries! If you could drop a comment on this thread when its resolved I'd appreciate it. Until then I've cloned a subtree of the repo in its current state. 

Thanks

**Comment by civerachb-cpr** [comment]
PR for releasing 0.3.1-1 is waiting.  Once that gets approved the package should get rebuilt & released.  Sorry it took so long.  (I recently took over as the maintainer and we had to sort out some permissions issues resulting from the handoff that slowed things down.)

In case you want to monitor the PR for the release, it's here: https://github.com/ros/rosdistro/pull/27799

**Comment by gmetts** [comment]
Thanks! Much appreciated. No worries about the delay, thanks for the active updates.

**Comment by civerachb-cpr** [comment]
The PR just got merged.  The updated release should be out as soon as the build farm rebuilds it and releases it.
