### ISSUE TITLE
AXIS PTZ M5525-e tested and it is working

### ISSUE THREAD

**Issue by Athapapa22** [ros-drivers/axis_camera#85]
Greetings,

Thanks for the ros pkg guys! I have tested the noetic devel branch with the M5525-E model and it is working fine after all the fixes with the python3 rosdep and the recomendation of  this guy: https://github.com/NVlabs/Deep_Object_Pose/issues/167#issuecomment-980771400
 
Also in order to get the image from the camera you must set the ecrypted_password=true

Thanks again you can add this axis model to the tested list as well.

**Comment by civerachb-cpr** [comment]
Great! Thanks for letting us know. I've updated the readme with a link to this report to indicate that at least one model from the M55 range has been tested.
